katalog/urls.py
# TODO: Implement Routings Here
from django.urls import path
from katalog.views import show_katalog

app_name = 'katalog'

urlpatterns = [
    path('', show_katalog, name='show_katalog'),
]

project_django/urls.py
from django.contrib import admin
from django.urls import path, include

# TODO: Implement Routings Here

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('example_app.urls')),
    path('katalog/', include('katalog.urls')),
    path('mywatchlist/', include('mywatchlist.urls')),
    path('todolist/', include('todolist.urls')),
]

todolist/urls.py
from django.urls import path

from .views import register
from .views import login_user
from .views import logout_user
from .views import show_todolist
from .views import create_task
from .views import set_status
from .views import delete_task
from .views import show_json
from .views import add_task
from .views import delete_task_async


app_name = 'todolist'

urlpatterns = [
    path('', show_todolist, name='show_todolist'),
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
    path('create-task/', create_task, name='create_task'),
    path('set-status/<int:id>', set_status, name='set_status'),
    path('delete-task/<int:id>', delete_task, name='delete_task'),
    path('json/', show_json, name='show_json'),
    path('add/', add_task, name='add_task'),
    path('delete/<int:id>', delete_task_async, name='delete_task_async'),
]

todolist/models.py
from email.policy import default
from operator import mod
from django.db import models
from django.contrib.auth.models import User
# Create your models here.

class Task(models.Model):
    user = models.ForeignKey(to=User, on_delete=models.CASCADE)
    date = models.DateField()
    title = models.CharField(max_length=255)
    description = models.TextField()
    is_finished = models.BooleanField(default=False)
    

    

todolist/forms.py
from django import forms
from .models import Task


class Input_Form(forms.ModelForm):
    class Meta:
        model = Task
        fields = [
            'title', 
            'description',
            ]

        labels = {
            'title' : 'Task Name',
            'description' : 'Task Description'
        }

        input_attrs = {
            'type' : 'text',
            'placeholder' : 'Nama task',
        }

        input_attrs2 = {
            'type' : 'text',
            'placeholder' : 'Deskripsi task',
        }

        widgets = {
            'title' : forms.TextInput(attrs=input_attrs),
            'description' : forms.TextInput(attrs=input_attrs2),
        }

todolist/views.py
from urllib import request
from django.shortcuts import render
from .models import Task

from django.shortcuts import redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages

from django.contrib.auth import authenticate, login

from django.contrib.auth import logout

from django.contrib.auth.decorators import login_required

# For cookies
import datetime
from django.http import HttpResponseRedirect, HttpResponse, HttpResponseNotFound
from django.urls import reverse

from .forms import Input_Form


from django.core import serializers

from django.http import JsonResponse

# Create your views here.

@login_required(login_url='/todolist/login/')
def show_todolist(request):
    todolist_objects = Task.objects.filter(user = request.user)
    context  = {
        'todolist_list' : todolist_objects,
        # 'last_login': request.COOKIES['last_login'],
    }
    return render(request, "todolist.html", context)

def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Akun telah berhasil dibuat!')
            return redirect('todolist:login')
    
    context = {'form':form}
    return render(request, 'register.html', context)


def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user) # melakukan login terlebih dahulu
            response = HttpResponseRedirect(reverse("todolist:show_todolist")) # membuat response
            #response.set_cookie('last_login', str(datetime.datetime.now())) # membuat cookie last_login dan menambahkannya ke dalam response
            return response
        else:
            messages.info(request, 'Username atau Password salah!')
    context = {}
    return render(request, 'login.html', context)

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('todolist:login'))
    #response.delete_cookie('last_login')
    return response

def create_task(request):
    response = {'input_form' : Input_Form}
    if request.method == 'POST':
        user = request.user
        form = Input_Form(request.POST or None)
        form.instance.date = datetime.datetime.now()
        form.instance.user = user
        if(form.is_valid and request.method == 'POST'):
            form.save()
            # return HttpResponseRedirect('/todolist')
        # else:
        #     return HttpResponseRedirect('/todolist')
    
    return render(request, 'create-task.html', response)

def delete_task(request, id):
    task_objects = Task.objects.get(pk=id)
    task_objects.delete()

    return HttpResponseRedirect(reverse("todolist:show_todolist"))

def set_status(request, id):
    task_object = Task.objects.get(pk=id)
    if(task_object.is_finished):
        task_object.is_finished = False
    else:
        task_object.is_finished = True
    task_object.save()
    return HttpResponseRedirect(reverse("todolist:show_todolist"))
   
def show_json(request):
    print("asijdoasdjka")
    todolist_objects = Task.objects.filter(user = request.user)
    return HttpResponse(serializers.serialize("json", todolist_objects), content_type="application/json")

# def add_task(request):
#     response = {'input_form' : Input_Form}
#     if request.method == 'POST':
#         userLogged = request.user
#         form = Input_Form(request.POST or None)
#         form.instance.date = datetime.datetime.now()
#         form.instance.user = userLogged
#         if(form.is_valid):
#             dataFields = form.cleaned_data
#             todo = Task.objects.create(**dataFields, user=userLogged)
#             response = {
#                 "pk":todo.pk,
#                 "fields":{
#                     "title": todo.title,
#                     "description":todo.description,
#                     "date":todo.date,
#                     "is_finished":todo.is_finished
#                 }
#             }

#     return JsonResponse(response)
def add_task(request):
    if request.method == 'POST':
        user = request.user
        title = request.POST.get("title")
        description = request.POST.get("description")
        date = datetime.datetime.now()

        new_task = Task(user=user, title=title, description=description, date=date)
        new_task.save()

        return HttpResponse(b"CREATED", status=201)

    return HttpResponseNotFound()



def delete_task_async(request, id):
    if(request.method == 'GET'):
        task_objects = Task.objects.get(pk=id)
        task_objects.delete()

        return HttpResponse(b"DELETED", status=201)
    return HttpResponseNotFound()

todolist/templates/create-task.html
{% extends 'base.html' %}

{% block meta %}
<title>Create your task here</title>
{% endblock meta %}

{% block content %}  

<body>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container-fluid">
          <a class="navbar-brand" href="https://cata-log.herokuapp.com/todolist">To-Do List</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="https://cata-log.herokuapp.com/todolist">Home</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="{% url 'todolist:create_task' %}">Create-Task</a>
              </li>
              <li class="nav-item">
                <a class="nav-link logout" href="{% url 'todolist:logout' %}">Logout</a>
              </li>
            </ul>
            <form class="d-flex" role="search">
              <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
              <button class="btn btn-outline-success" type="submit">Search To-Do</button>
            </form>
          </div>
        </div>
      </nav>
    
    <div class="create-task-container justify-content-center align-self-center d-flex h-100">
    
        <div class = "create-task ">
    
            <h3>Add your new task here.</h3>
            <br>
    
            <table>
                <form method="POST">
                    {% csrf_token %}
                    
                    <tr>
                        <td>{{input_form.as_p}}</td>
                    </tr>
                    <tr>
                        <td><input type="submit" value="add"></td>
                    </tr>
                </form>
        
            </table>
        </div>  
    
    
    </div>
</body>

{% endblock content %}

todolist/templates/login.html
{% extends 'base.html' %}

{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
<title>Login</title>

{% endblock meta %}

{% block content %}

    <div class="login-container">
            <div class="login-dark">
                <form method="POST" action="">
                    {% csrf_token %}
                        <h2 class="sr-only">Login</h2>
                        <div class="illustration"><i class="icon ion-ios-locked-outline"></i></div>
                        <div class="form-group"><input class="form-control"  name="username" placeholder="username"></div>
                        <div class="form-group"><input class="form-control" type="password" name="password" placeholder="Password"></div>
                        <div class="form-group"><button class="btn btn-primary btn-block" type="submit">Log In</button></div>
                </form>

            </div>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
                <script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.1.3/js/bootstrap.bundle.min.js"></script>
            
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                    {% endfor %}
                </ul>
            {% endif %}     

            Belum mempunyai akun? <a href="{% url 'todolist:register' %}">Buat Akun</a>
                
        
        </div>

    </div>
    

    <script>
    function register() {
        return fetch("{% url 'todolist:register' %}");
    }
    </script>
    

{% endblock content %}

todolist/templates/register.html
{% extends 'base.html' %}

{% block meta %}
<title>Registrasi Akun</title>
{% endblock meta %}

{% block content %}  


<body>

    <div class="register-container justify-content-center align-self-center d-flex h-100">
        <div class = "register">
        
            <h1>Formulir Registrasi</h1>  
            
            <form method="POST" >  
                {% csrf_token %}  
                <table>  
                    {{ form.as_table }}  
                    <tr>  
                        <td></td>
                        <td><input type="submit" name="submit" value="Daftar"/></td>  
                    </tr>  
                </table>  
            </form>
        
        </div>  
            
        <div>
            {% if messages %}  
            <ul>   
                {% for message in messages %}  
                    <li>{{ message }}</li> 
                {% endfor %}  
            </ul>   
            {% endif %}  
        </div>

    </div>

</body>

{% endblock content %}

todolist/templates/todolist.html
{% extends 'base.html' %}

{% block meta %}
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
{% endblock meta %}


{% block content %}

 
 <script>

  async function getTodo() {
    return fetch("{% url 'todolist:show_json' %}").then((res) => res.json())
  }

  async function refreshTodolist() {
      
        const todo = await getTodo();
        console.log("TESSSSSSSS" + " " + todo + " aa");
        let htmlString = ''
        todo.forEach((item) => {
          htmlString += `\n
          <div class="flex-container justify-content-center align-self-center d-flex h-100""">
            <div class="card" style="width: 18rem;">
              <img src="https://tse1.mm.bing.net/th?id=OIP.lR17CZXTy9_eI8zq4t6fUAHaEK&pid=Api&P=0" class="card-img-top" alt="...">
              <div class="card-body">
                <h5 class="card-title">${item.fields.title}</h5>
                <p class="card-title">${item.fields.description}</h5>
              </div>
              <ul class="list-group list-group-flush">
                <li class="list-group-item">Tanggal pembuatan: ${item.fields.date}</li>
                <li class="list-group-item"> Status: ${item.fields.is_finished ? "Finished" : "Unfinished"} </li>
              </ul>
              <div class="card-body">
                <a href="set-status/${item.pk}" class="card-link">Ubah</a>
                <button type="button" id="button-delete" class="btn btn-primary" onclick="deleteTodo(${item.pk})">Delete</button>
              </div>
            </div>
          </div>
          ` 
        })
        document.getElementById("content").innerHTML = htmlString
  }

  function addTodo() {
    console.log("TES")
    fetch("{% url 'todolist:add_task' %}", {
          method: "POST",
          body: new FormData(document.querySelector('#form'))
      }).then(refreshTodolist)
    return false
  }

  function deleteTodo(todoPK) {
    console.log("TESzzz")
    fetch(`/todolist/delete/${todoPK}`, {
      method: "GET",
      }
      ).then(refreshTodolist)
    return false
  }


  refreshTodolist()  
  // document.getElementById("addbtn").onclick = addTodo

  // function showModal(){
  //   document.getElementById("#button").show(document.getElementById("#staticBackdrop"));
  
  // }
  // $('#btn').on('click', function(){
  //   $('#staticBackdrop').modal('show');
  // });


  </script>

  <body>

    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Your To-Do List</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="https://cata-log.herokuapp.com/todolist">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'todolist:create_task' %}">Create-Task</a>
            </li>
            <li class="nav-item">
              <a class="nav-link logout" href="{% url 'todolist:logout' %}">Logout</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search To-Do</button>
          </form>
        </div>
      </div>
    </nav>

    <br>

    <div id="content">
    </div>

<!-- Button trigger modal -->
    <div class="text-center">
      <button type="button" id="button-modal" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#staticBackdrop">
        Add Task
      </button>
    </div>

<!-- Modal -->
    <div class="modal fade" id="staticBackdrop" role="dialog" data-bs-backdrop="static" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="staticBackdropLabel">Add your new task </h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
          <form id="form" method="POST" onsubmit="return false;">
            <div class="modal-body">
                {% csrf_token %}
                <div class="form-group">
                    <label for="title" class="col-form-label">Title:</label>
                    <input type="text" class="form-control" id="title" name="title">
                </div>
                <div class="form-group">
                    <label for="description" class="col-form-label">Description:</label>
                    <input type="text" class="form-control" id="description" name="description">
                </div>
      
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button type="button" id="addbtn" class="btn btn-primary" onclick="addTodo()">Add</button>
            </div>
          </form>
        </div>
      </div>
    </div>

  <!-- <h5>Sesi terakhir login: {{ last_login }}</h5> -->
  </body>

  {% endblock content %}